name: Compile and Test

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install erlang
        run: sudo apt update && sudo apt install -y erlang
      - name: Install mond
        run: cargo install --git https://github.com/benjaminjellis/mond.git --tag 0.0.4 mond
      - name: Build
        run: mond build
      - name: Test
        run: mond test
